### PR TITLE
fix: jax moved tree_util. fix deprecated warnning

### PR DESCRIPTION
**Pull request by jinmingyi1998**
https://github.com/google/jax/blob/c1192f383750d5d64a69c19914b7481239b9a327/jax/__init__.py#L120

jax remove `jax.tree_xxx` . use `jax.tree_util.tree_xxx` instead

### CODE REVIEW

**Comment by jinmingyi1998** [comment]
start from jax - 0.3.15

**Comment by Augustin-Zidek** [comment]
Thanks, fixed in v2.3.0.

**Comment by JTT94** [comment]
`
  File "<stdin>", line 1, in <module>
AttributeError: module 'jax.tree_util' has no attribute 'tree_multimap'
`

I dont think it is fixed?

Using 
`jax==0.3.25
jaxlib==0.3.25+cuda11.cudnn82`

**Comment by jinmingyi1998** [comment]
> `File "<stdin>", line 1, in <module> AttributeError: module 'jax.tree_util' has no attribute 'tree_multimap'`

this pr is not for your error.

I think you need to pull the latest code. there is not "tree_multimap" in the code

**Pull request closed without merging**
