### PR TITLE
Changes to avoid reading the whole MSA files into the memory thus Memory Errors

### PR DESCRIPTION
**Pull request by hegelab**
Sequence searches may result in alignment file (over 100GB).
The original AF2 code reads the whole file into memory and parses there that may cause out of memory error.

Our modifications implement the line-by-line reading of MSA files thus decrease the required RAM size for AF2 predictions.

### CODE REVIEW

**Comment by Augustin-Zidek** [comment]
Hi, this is a great change. Could you sign the CLA?

**Comment by hegelab** [comment]
I do not know what would be the best way to do it.
Accidentally I submitted it with an unexisting email address. I could not figure out what to do:
I think I should resubmit it with valid email address and sign. However, then this request will be doubled.
???

**Comment by Augustin-Zidek** [comment]
Sorry about that! Could you resubmit with the valid email address and sign? I will close this PR once you have done that to prevent duplication.

**Comment by hegelab** [comment]
I will do it later today or early tomorrow

**Comment by Augustin-Zidek** [comment]
Thank you.

**Comment by hegelab** [comment]
I resubmitted a new pull req. Pls. let me know if something is still wrong - I am new to git.

**Pull request closed without merging**
