### PR TITLE
Changes to avoid reading the whole MSA files into the memory - w fixed author

### PR DESCRIPTION
**Pull request by hegelab**
Sequence searches may result in alignment file (over 100GB).
The original AF2 code reads the whole file into memory and parses there that may cause out of memory error.

Our modifications implement the line-by-line reading of MSA files thus decrease the required RAM size for AF2 predictions.

### CODE REVIEW

**Comment by Augustin-Zidek** [comment]
Thank you! We will do a bug fix release next week and a fix based on this PR will be included together with a few other fixes. I will close the PR once the bug fix is released.

**Comment by hegelab** [comment]
Are you interested in impoving the pipeline configuration? It is not a bug-fix, but it could help users with smaller resources (as we) a lot.

I split up the code of run_alphafold.py/predict_structure function to three parts: generataion of alignments, running the models (output is unrelaxed pdb files), and relaxation. Implemented via a configuration file; it could be done easily via command line arguments, but I already find the current command line pretty heavy. Similarly as I done with the first release of AF2 - see https://github.com/hegelab/betafold. I am almost ready with the new release, but I need time for testing. I would not accelerate this if you do not need it in a week.

**Comment by kdpan** [comment]
> Sequence searches may result in alignment file (over 100GB). The original AF2 code reads the whole file into memory and parses there that may cause out of memory error.
> 
> Our modifications implement the line-by-line reading of MSA files thus decrease the required RAM size for AF2 predictions.

I'v done  modifications implement the line-by-line reading of MSA files, but it still have an **out of memory erro**:_RuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 13013345720 bytes._

**Comment by hegelab** [comment]
I see two possibilities:
* you have low amount of memory; I still see high RAM usage after code modification, up to 60-80GB
* you may not have done all the modifications I did; you should clone my fork and try it (https://github.com/hegelab/alphafold); if you still have problem, share your input and I try to test it

**Comment by kdpan** [comment]
> Are you interested in impoving the pipeline configuration? It is not a bug-fix, but it could help users with smaller resources (as we) a lot.
> 
> I split up the code of run_alphafold.py/predict_structure function to three parts: generataion of alignments, running the models (output is unrelaxed pdb files), and relaxation. Implemented via a configuration file; it could be done easily via command line arguments, but I already find the current command line pretty heavy. Similarly as I done with the first release of AF2 - see https://github.com/hegelab/betafold. I am almost ready with the new release, but I need time for testing. I would not accelerate this if you do not need it in a week.

I've 

> I see two possibilities:
> 
> * you have low amount of memory; I still see high RAM usage after code modification, up to 60-80GB
> * you may not have done all the modifications I did; you should clone my fork and try it (https://github.com/hegelab/alphafold); if you still have problem, share your input and I try to test it

**@hegelab**  
**Sorry, the Error occurred at running models not generating features. Do you know how to solve it?**

_

```
Traceback (most recent call last):
  File "run_alphafold.py", line 439, in <module>
    app.run(main)
  File "/home/panfulu/anaconda3/envs/alphafold/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/panfulu/anaconda3/envs/alphafold/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "run_alphafold.py", line 415, in main
    predict_structure(
  File "run_alphafold.py", line 205, in predict_structure
    prediction_result = model_runner.predict(processed_feature_dict,
  File "/home/panfulu/project/alphafold/alphafold/model/model.py", line 167, in predict
    result = self.apply(self.params, jax.random.PRNGKey(random_seed), feat)
  File "/home/panfulu/anaconda3/envs/alphafold/lib/python3.8/site-packages/jax/_src/dispatch.py", line 436, in _execute_compiled
    out_bufs = compiled.execute(input_bufs)
RuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 13013345720 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    1.03GiB
              constant allocation:    38.6KiB
        maybe_live_out allocation:  269.16MiB
     preallocated temp allocation:   12.12GiB
  preallocated temp fragmentation:    1.15GiB (9.48%)
                 total allocation:   13.41GiB
              total fragmentation:    1.16GiB (8.68%)
Peak buffers:
        Buffer 1:
                Size: 1.17GiB
                XLA Label: parameter
                Shape: f32[5120,961,64]
                ==========================

        Buffer 2:
                Size: 1.17GiB
                XLA Label: parameter
                Shape: f32[5120,961,64]
                ==========================

        Buffer 3:
                Size: 1.17GiB
                Operator: op_type="add" op_name="jit(apply_fn)/body/body/add" source_file="/home/panfulu/anaconda3/envs/alphafold/lib/python3.8/site-packages/haiku/_src/layer_norm.py" source_line=145
                XLA Label: fusion
                Shape: f32[5120,961,64]
                ==========================

        Buffer 4:
                Size: 1.17GiB
                Operator: op_type="broadcast_in_dim" op_name="jit(apply_fn)/body/body/broadcast_in_dim[\n  broadcast_dimensions=()\n  shape=(5120, 961, 64)\n]" source_file="/home/panfulu/project/alphafold/alphafold/model/mapping.py" source_line=177
                XLA Label: broadcast
                Shape: f32[5120,961,64]
                ==========================

        Buffer 5:
                Size: 1.17GiB
                Operator: op_type="add" op_name="jit(apply_fn)/add" source_file="/home/panfulu/project/alphafold/alphafold/model/common_modules.py" source_line=127
                XLA Label: fusion
                Shape: f32[5120,961,64]
                ==========================

        Buffer 6:
                Size: 901.88MiB
                Operator: op_type="broadcast_in_dim" op_name="jit(apply_fn)/broadcast_in_dim[broadcast_dimensions=() shape=(4, 961, 961, 64)]" source_file="/home/panfulu/project/alphafold/alphafold/model/mapping.py" source_line=177
                XLA Label: broadcast
                Shape: f32[4,961,961,64]
                ==========================

        Buffer 7:
                Size: 480.50MiB
                Operator: op_type="concatenate" op_name="jit(apply_fn)/body/concatenate[dimension=0]" source_file="/home/panfulu/project/alphafold/alphafold/model/modules.py" source_line=1873
                XLA Label: fusion
                Shape: f32[512,961,256]
                ==========================

        Buffer 8:
                Size: 476.75MiB
                XLA Label: custom-call
                Shape: f32[488188,256]
                ==========================

        Buffer 9:
                Size: 450.94MiB
                XLA Label: parameter
                Shape: f32[961,961,128]
                ==========================

        Buffer 10:
                Size: 450.94MiB
                XLA Label: copy
                Shape: f32[961,961,128]
                ==========================

        Buffer 11:
                Size: 450.94MiB
                XLA Label: copy
                Shape: f32[961,961,128]
                ==========================

        Buffer 12:
                Size: 450.94MiB
                XLA Label: copy
                Shape: f32[961,961,128]
                ==========================

        Buffer 13:
                Size: 450.94MiB
                Operator: op_type="broadcast_in_dim" op_name="jit(apply_fn)/body/body/broadcast_in_dim[\n  broadcast_dimensions=()\n  shape=(961, 961, 128)\n]" source_file="/home/panfulu/project/alphafold/alphafold/model/mapping.py" source_line=177
                XLA Label: broadcast
                Shape: f32[961,961,128]
                ==========================

        Buffer 14:
                Size: 450.94MiB
                XLA Label: custom-call
                Shape: f32[923521,128]
                ==========================

        Buffer 15:
                Size: 450.94MiB
                Operator: op_type="broadcast_in_dim" op_name="jit(apply_fn)/broadcast_in_dim[broadcast_dimensions=() shape=(923521, 1, 128)]" source_file="/home/panfulu/project/alphafold/alphafold/model/mapping.py" source_line=177
                XLA Label: broadcast
                Shape: f32[923521,1,128]
                ==========================
```

_

**Comment by hegelab** [comment]
Get a GPU with more memory you have now.
I was able to run predictions on a 24GB card up to ~1,500 a.a. length.
I guess you need 40-48GB card up to ~2,000 a.a.
Even deep mind did not make predictions above 2,000 a.a. (at least not in the first release of AF2 db at EBI).

**Comment by Augustin-Zidek** [comment]
Thanks @hegelab, I added a fix heavily inspired by your solution in https://github.com/deepmind/alphafold/commit/57a2455e5fab752d8df430ae1d0334e1a21b548c

**Pull request closed without merging**
